[package]
name = "async-chat-room"
version = "0.1.0"
authors = ["swzhxx <549909896@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.0"
async-std = "1"